data:
  image: busybox
  volumes:
    - .:/data

db:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: robohome
    MYSQL_ROOT_PASSWORD: password

web:
  image: choqco/dk-laravel:php71
  ports:
    - "80:80"
  volumes_from:
    - data
  links:
    - db
  environment:
    MYSQL_HOST: db

dbadmin:
  image: phpmyadmin/phpmyadmin:4.7
  ports:
    - "8183:80"
  links:
    - db
